# Generated by Django 5.1.1 on 2024-09-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=16)),
                ("practice_name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=32)),
                ("address1", models.CharField(max_length=100)),
                ("address2", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("zip", models.CharField(max_length=10)),
                ("website", models.URLField(blank=True)),
                ("license", models.CharField(max_length=64)),
            ],
        ),
    ]
